<a href="https://colab.research.google.com/github/rakshamishra54/NLP_Notebooks/blob/main/Word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
path = "/content/drive/MyDrive/IMDB Dataset.csv"

temp_df = pd.read_csv(path)

In [4]:
df = temp_df.iloc[:10000]

In [5]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [7]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(17)

In [10]:
df.drop_duplicates(inplace=True)

/tmp/ipykernel_2629/3617111529.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
import re
def remove_tags(text):
    return re.sub(r'<.*?>', ' ', text)

df['review'] = df['review'].apply(remove_tags)
df['review'].head()

/tmp/ipykernel_2629/56729436.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)

0    One of the other reviewers has mentioned that ...
1    A wonderful little production.   The filming t...
2    I thought this was a wonderful way to spend ti...
3    Basically there's a family where a little boy ...
4    Petter Mattei's "Love in the Time of Money" is...
Name: review, dtype: object

In [13]:
df['review'] =df['review'].apply(remove_tags)

/tmp/ipykernel_2629/3061868794.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] =df['review'].apply(remove_tags)

In [14]:
df

                                                 review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production.   The filming t...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [15]:
df['review'] = df['review'].apply(lambda x:x.lower())

/tmp/ipykernel_2629/3523187300.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())

In [16]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x: " ".join(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
/tmp/ipykernel_2629/1885752193.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x: " ".join(x))

In [17]:
df

                                                 review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [18]:

X = df.iloc[:,0:1]
y = df['sentiment']

In [19]:
X

                                                 review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [20]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size =0.2 , random_state=1)

In [22]:
X_train.shape

(7986, 1)

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
cv = CountVectorizer()

In [25]:
X_train_bow =cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [26]:
X_train_bow.shape

(7986, 47917)

In [27]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow , y_train)

GaussianNB()

In [28]:
y_pred =gnb.predict(X_test_bow)
from sklearn.metrics import accuracy_score , confusion_matrix
accuracy_score(y_test , y_pred)

0.6314471707561342

In [29]:
confusion_matrix(y_test, y_pred)

array([[716, 236],
       [500, 545]])

In [30]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_bow , y_train)
y_pred =rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8482724086129194

In [31]:
cv = CountVectorizer(ngram_range=(1,3),max_features =5000)
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow ,y_train)
y_pred= rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8442663995993991

###Using TfIdf

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
tfidf =TfidfVectorizer()

In [34]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [35]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8437656484727091

In [37]:
!pip install gensim
import gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.5.0)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 36.7 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [44]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [45]:
story = []
for doc in df['review']:

  raw_sent = sent_tokenize(doc)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [46]:
model = gensim.models.Word2Vec(
    window =10,
    min_count =2
)

In [47]:
model.build_vocab(story)

In [48]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5818556, 6144805)

In [49]:
len(model.wv.index_to_key)

31845

In [50]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [52]:
document_vector(df['review'].values[0])

array([-0.08105288,  0.33656606,  0.15780628, -0.03867215,  0.05366052,
       -0.5668088 ,  0.22277677,  0.6675013 , -0.09482353, -0.21712695,
       -0.10509325, -0.37418547, -0.03774951,  0.09078991,  0.1200741 ,
       -0.20759699,  0.23497987, -0.28515664, -0.04230162, -0.54675007,
        0.27381998,  0.09483381,  0.03536583, -0.34556964, -0.01116398,
       -0.17309456, -0.3427317 , -0.20271026, -0.16412827, -0.0339855 ,
        0.41874844, -0.00191305,  0.10497782, -0.48288286, -0.12559117,
        0.47124335,  0.1425243 , -0.19835699, -0.22143073, -0.78953165,
        0.11284131, -0.19108133, -0.15827149, -0.12276173,  0.24987148,
       -0.30138236, -0.5225583 ,  0.09719607,  0.06352013,  0.37258318,
        0.37019658, -0.4663867 , -0.23376082, -0.26639628, -0.28576136,
        0.3721044 ,  0.31559741,  0.10252473, -0.3451393 ,  0.23565869,
        0.06282495,  0.12789106, -0.07294261,  0.17009275, -0.37040567,
        0.31517285, -0.05317486,  0.01249981, -0.3699085 ,  0.15047897,
       -0.14335479, -0.01907688,  0.46903166, -0.06067048,  0.34306508,
        0.10874068,  0.01117111, -0.04556144, -0.45198506,  0.28914464,
       -0.23614801, -0.02334302, -0.379654  ,  0.50177735, -0.1224061 ,
        0.07844751,  0.14982978,  0.37410778,  0.49465346,  0.29600197,
        0.49266055,  0.14923726,  0.11360876,  0.07384139,  0.8874055 ,
        0.2857051 ,  0.27606532, -0.43282753,  0.1846686 ,  0.0573576 ],
      dtype=float32)

In [53]:
from tqdm import tqdm

In [54]:
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [18:29<00:00,  9.00it/s]

In [55]:
X = np.array(X)

In [56]:
X[0]

array([-0.08105288,  0.33656606,  0.15780628, -0.03867215,  0.05366052,
       -0.5668088 ,  0.22277677,  0.6675013 , -0.09482353, -0.21712695,
       -0.10509325, -0.37418547, -0.03774951,  0.09078991,  0.1200741 ,
       -0.20759699,  0.23497987, -0.28515664, -0.04230162, -0.54675007,
        0.27381998,  0.09483381,  0.03536583, -0.34556964, -0.01116398,
       -0.17309456, -0.3427317 , -0.20271026, -0.16412827, -0.0339855 ,
        0.41874844, -0.00191305,  0.10497782, -0.48288286, -0.12559117,
        0.47124335,  0.1425243 , -0.19835699, -0.22143073, -0.78953165,
        0.11284131, -0.19108133, -0.15827149, -0.12276173,  0.24987148,
       -0.30138236, -0.5225583 ,  0.09719607,  0.06352013,  0.37258318,
        0.37019658, -0.4663867 , -0.23376082, -0.26639628, -0.28576136,
        0.3721044 ,  0.31559741,  0.10252473, -0.3451393 ,  0.23565869,
        0.06282495,  0.12789106, -0.07294261,  0.17009275, -0.37040567,
        0.31517285, -0.05317486,  0.01249981, -0.3699085 ,  0.15047897,
       -0.14335479, -0.01907688,  0.46903166, -0.06067048,  0.34306508,
        0.10874068,  0.01117111, -0.04556144, -0.45198506,  0.28914464,
       -0.23614801, -0.02334302, -0.379654  ,  0.50177735, -0.1224061 ,
        0.07844751,  0.14982978,  0.37410778,  0.49465346,  0.29600197,
        0.49266055,  0.14923726,  0.11360876,  0.07384139,  0.8874055 ,
        0.2857051 ,  0.27606532, -0.43282753,  0.1846686 ,  0.0573576 ],
      dtype=float32)

In [57]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [58]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [77]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [78]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test, y_pred)

0.7706559839759639